### ISSUE TITLE
What is the license for it?

### ISSUE THREAD

**Issue by vinkaga** [searchy2/FlutterGames#2]
I'd like to use this project as a starter for my flutter application. I want to make sure such use is acceptable to the authors. 

If it is the desired goal of this app, I'd also recommend setting license to "unlicense" https://choosealicense.com/licenses/unlicense/ .

**Comment by rayliverified** [comment]
Hi @vinkaga, thanks for prompting me to add a license. 

I maintain this project because I find it is a useful testbed for new Flutter features and projects. Glad to see it help you too. 

I've released FlutterGames under the BSD Zero Clause License unencumbered, so anyone can do with it as they wish!

**Comment by vinkaga** [comment]
Perfect! Thanks for updating it so quickly.

**Comment by rayliverified** [comment]
You're welcome :)
